### PR TITLE
Add note about `malloc_usable_size` (fixes #278)

### LINKED ISSUE #278: malloc_usable_size incompatible with _FORTIFY_SOURCE=3
Some applications use malloc_usable_size (despite the glibc manual stating it is for diagnostic purposes only). This is currently incompatible with _FORTIFY_SOURCE=3. This should be documented in the compiler options guide.

https://archlinux.org/todo/prepare-packages-for-d_fortify_source3/

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This fixes #278.

**Comment by thomasnyman** [comment]
Merged @david-a-wheeler's note with @siddhesh's note. Add missing reference to glibc manual page for `malloc_usable_size(3)`.

**Review by thomasnyman — APPROVED** [review]

**Comment by david-a-wheeler** [comment]
+1 for your change. Thanks, @thomasnyman !

**Comment by david-a-wheeler** [comment]
All seem happy. I'll merge.

**Pull request merged**
