### PR TITLE
Update SecureSoftwareGuidingPrinciples.md

### PR DESCRIPTION
**Pull request by SecurityCRob**

### CODE REVIEW

**Review by ware — APPROVED** [review]
+1

**Comment by lehors** [comment]
I think Signees is a better name for this than Signatures.

**Comment by david-a-wheeler** [comment]
+1

**Review by sevansdell — COMMENTED** [review]
out of sight!

**Comment by sevansdell** [comment]
A couple comments from Jordan Harband in Slack... (not sure how to suggest edits other than this, so please provide on-the-job-training and I will apply these where needed): 

- s/open source software)/open source software.
- principle 2: recommend "least privilege" link to https://csrc.nist.gov/glossary/term/least_privilege
- Principle 3: "the most common kinds of vulnerabilities in our software's problem domain"
- Principle 8: can you elaborate on "inclusive of upstream dependencies"? (open to team feedback here)

**Pull request merged**
