### PR TITLE
Use OpenSSF fonts

### PR DESCRIPTION
**Pull request by david-a-wheeler**
I'm not sure the URLs are correct here, we may need to experiment. This code means we serve our fonts.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
If anyone has experience with tweaking fonts like this, please let me know. I'm trying to switch to the "basics".

**Comment by david-a-wheeler** [comment]
This is a *small* step towards implementing [issue 160](https://github.com/ossf/wg-best-practices-os-developers/issues/160), that is, to implement the draft [OpenSSF branding guidelines](https://openssf.org/brand-guidelines/) by using the current proposed fonts.

NB: There appear to be some questions about these fonts, perhaps we should wait until that's examined.

Any comments? Esp: @hythloda @SecurityCRob @jennbly ?

**Comment by david-a-wheeler** [comment]
I think we should merge this & tweak if necessary to change the fonts. Even if we decide to use another font, it's at least a step towards configuring the generated web pages to look like we want them to look.

**Comment by jennbly** [comment]
I'd agreed to go ahead and move forward with the proposed fonts as a good start in the right direction. And then once we have investigated the concerns and solutions with the design & web teams, if changes are needed, we can adjust accordingly.

**Comment by david-a-wheeler** [comment]
Ok, per recommendation I'll merge this and we can see what it looks like.

My experience with CSS is that you often have to twiddle things to "get it right". Eventually we'll probably want one OpenSSF-wide repo that lets us update the CSS for all, but for now, let's get it working.

**Comment by david-a-wheeler** [comment]
You can currently see the results here:

https://bp.openssf.org/Concise-Guide-for-Developing-More-Secure-Software.html

Now that I can see it, Ihe lack of serifs is unfortunate for when you have a lot of text. Are we sure we want a sans-serif font for this case?? I also think the heading font is excessively blocky, though that's just a personal preference. However, we have switched to the recommended format, and now we can be confident that we could switch again later.

Since there is no color on most of the guidebooks, there are no colors to change. Maybe I can call this "done"?

**Pull request merged**
