### PR TITLE
Propose adding 2 new principles

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Add one on design and one on implementation.
This also fixes a trailing whitespace.

I renumbered all the entries; this increases the risk of a merge conflict, but markdownlint will complain if I don't do it.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@jkmarz - what do you think?

**Comment by jkmarz** [comment]
@david-a-wheeler I'm of two minds... first thought is, could these be considered part of "modern software development practices" and could be moved to implementation guide? Second thought is, if added as principles, would be stronger without "where practical" language --- OK to remove?

**Comment by david-a-wheeler** [comment]
Ok to remove "where practical", I'll do that.

You could argue everything listed here are "modern software development practices". I think these points add specifics that are important while still staying high-level.

**Comment by david-a-wheeler** [comment]
I'll note that a majority of the course on developing secure software can be summarized by these two new principles.

**Review by jkmarz — APPROVED** [review]

**Comment by david-a-wheeler** [comment]
Thanks for the approval!

I believe this resolves the substantive comments from the best practices WG meeting today, where some wanted something about design and implementation. It also resolves the CI/CD errors (by fixing the markdown).

Since @jkmarz was the original proposer & approved this change, I'll just merge this. If that's in error, please revert.

**Pull request merged**
