### PR TITLE
Add Concise Guide for Evaluating Open Source Software

### PR DESCRIPTION
**Pull request by ran-dall**
This PR adds the "Concise Guide for Evaluating Open Source Software" document to the repository.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
The nested (sub) bullets didn't get translated correctly. On GitHub they just show as a long list of numbers:

https://github.com/ossf/wg-best-practices-os-developers/blob/2cfccd6ed400b535e216b44d45b8d010e1ea787d/docs/Concise-Guide-for-Evaluating-Open-Source-Software.md

[Nested lists have to be indented by 4 spaces per CommonMark](https://commonmark.org/help/tutorial/10-nestedLists.html). These are only indented 2 spaces.

I suspect that if you search & replace all lines with a leading 2 spaces with 4 spaces, much will be fixed.

**Comment by david-a-wheeler** [comment]
Also, the translator seems to have converted curly quotes into straight quotes. I suggest just copy/paste the UTF-8 curling quotes in the right places (there aren't many).

**Comment by david-a-wheeler** [comment]
I presume these comments will also apply to PR #73.

**Comment by david-a-wheeler** [comment]
Thanks for doing the translation!

**Comment by david-a-wheeler** [comment]
Also: In the commit message you need to add at the bottom:

> Signed-off-by: YOUR_NAME <YOUR_EMAIL_ADDRESS>

For more information, see: https://github.com/ossf/tac/blob/main/dco.md

You might just want to do the fixes & create a new pair of pull requests.

**Comment by ran-dall** [comment]
@david-a-wheeler Thank you for the review. Sorry about the issues.

> The nested (sub) bullets didn't get translated correctly. 

Yup, my bad, the Commonmark Linter didn't execute the document formatting the first time correctly. It's fixed now.

> Also, the translator seems to have converted curly quotes into straight quotes. I suggest just copy/paste the UTF-8 curling quotes in the right places (there aren't many).

I'm not sure why it didn't work. I specifically told it to use UTF-8 encoding. Regardless, I fixed it manually, though.

> Also: In the commit message you need to add at the bottom:

I'm using `--signoff` when I did the commit. I've attached the screenshot below. Maybe I'm doing it wrong?

image

I'll force-push the changes to both PRs shortly.

**Comment by david-a-wheeler** [comment]
> Yup, my bad, the Commonmark Linter didn't execute the document formatting the first time correctly.

I'm just grateful you did this! This is what reviews are all about, people find weirdnesses in some of my commits too :-).

> It's fixed now.

Great! GitHub seems to show it's unfixed, but I may be misunderstanding what it says. I'm going to just merge, and if it merges the older version we can still fix it later.

> I'm using --signoff when I did the commit.

That's right. Well, let's try to merge and see what happens.

**Pull request merged**
