### PR TITLE
Suggested change to point 7

### LINKED ISSUE #81: Vendor neutrality when it comes to tools
The current version of the [concise guide](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Concise-Guide-for-Developing-More-Secure-Software.md) lists:

> “Monitor known vulnerabilities in your software’s direct & indirect dependencies. E.g., use GitHub [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) & GitLab [dependency scanning](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/). Quickly update vulnerable dependencies.”

I'd like to suggest that this needs to be more vendor neutral, either by removing references to specific dependency tracking tools entirely or by listing more tools…?

### PR DESCRIPTION
**Pull request by torgo**
This intended to enhance neutrality while still providing most actionable advice and avoiding the NASCAR problem of listing all possible tools.

Resolves #81.

Signed-off-by: Daniel Appelquist <daniel.appelquist@snyk.com>

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
Re: DCO. The *commit* already exists. I don't know if this repo allows force pushes; if it does, you could use `git commit -asv --amend` to add the signoff, and then to a force-push (`git push -f`). I'd be curious to see if that works.

**Comment by david-a-wheeler** [comment]
Re: the suggestion itself - Thanks for the suggestion!

In *principle* it looks good, but I'd like to see a few tweaks. The original change:

> 7. **Monitor known vulnerabilities in your software’s direct & indirect dependencies**. E.g., use GitHub [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) & GitLab [dependency scanning](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/). Quickly update vulnerable dependencies.

Became:

> 7. **Monitor known vulnerabilities in your software’s direct & indirect dependencies**. E.g., if your  project is on GitHub, turn on [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) which provides basic scanning. Many other third party tools are also available.

Thanks so much. A few further suggestions:
* I think we need to re-add the GitLab reference. For examples we've been trying to make it clear they are examples (using "e.g.") *and* where reasonable listing at least 2 examples (again, for neutrality, to make it clear there isn't just one way to do this.
* We want to make this as short as we can while still being clear.
* I think we should add the term "SCA" to help people find them.
* Tell people to rapidly update, not just monitor. Obviously if they never update it doesn't matter :-).

How about this:

7. **Monitor known vulnerabilities in your software’s direct & indirect dependencies**. E.g., enable basic scanning via GitHub's [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) or GitLab [dependency scanning](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/). Many other third party Software Composition Analysis (SCA) tools are also available. Quickly update vulnerable dependencies.

**Comment by david-a-wheeler** [comment]
BTW, if you can't fix the commit, you can just close, recreate the commit with the signature, and create a new pull request.

**Comment by torgo** [comment]
Hi David - I think the proposed change is fine. Thanks for being open to it - much appreciated. My git mojo is failing me so I'm going to close this and re-create with the new proposed text.

**Pull request closed without merging**
