### PR TITLE
feat: add new argument injection lab

### PR DESCRIPTION
**Pull request by lirantal**
Hi @david-a-wheeler 👋

Got to stumble upon the OpenSSF Secure Coding Labs a couple of months back and really like the idea. Congrats on creating and launching this to you and all the team involved.

If you'd be interested in further expanding on some of the labs exercises I'm happy to contribute another lesson and lab on Argument Injection (a sub-class of command injection security issues).

This is an initial write-up for the lesson with the contents and if you'd want to welcome this in I'd gladly continue to add up the interactive bits for the HTML scripts that require the expected code and the hints/solution.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
Wow! Thank you *so much* for being willing to create labs! Time is the most precious gift.

The labs need to support LFD121, so there should be a clear section it supports. The list of sections we're hoping to create labs for is here:
https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/labs/README.md

This appears to be yet another OS Command (Shell) injection lab. That's *okay* - we can have multiple labs for a section. Indeed, our current command injection lab uses Python, so adding a JavaScript one has its plusses.

That said: we have so many unhandled sections that I would encourage you in the future to look at "not yet done" labs first. We already have injection labs either created or planned with someone else assigned:

* SQL Injection - DONE-1 (@Elijah Everett, 2024-08-13) sql-injection
* OS Command (Shell) injection - DONE-1 (Marta Rybczynska) shell-injection
* Other Injection Attacks - PLANNED-2 (Dhananjay Arunesh via Vincent Danen, 2026-07-26)

That said... this is an important topic, worthy of more than 1 lab. Let's presume you'll finish this off (I hope you will!). Please let me make some comments on the lab itself:

> Argument injection is a type of attack related to command injection.
It occurs when user-supplied input is passed unchecked into commands 
executed by an application.

This doesn't seem to be any different from command injection. You're allowing an attacker to create commands the attacker shouldn't be allowed to make :-).

In "task information" it duplicates the code. I don't see a need to show the code twice. I suggest just showing the code once.

The lab needs an expected answer, correct answer, and I would suggest adding hints. I can help, if you need help, but provide at least an *attempt* at what the correct answer should be instead, and we can tweak it from there. Make sure the correct answer is actually correct :-).

Thanks again!!

**Comment by lirantal** [comment]
Happy to join in on the effort :-)

I'll attend your comments to improve the description, remove the duplication and add an initial expected, and correct answer (will give the hints a go too). Once we land this one I'm happy to take on another lab listed that is unassigned.

**Comment by elijah** [comment]
I think you meant to tag @Wavyeli32 but I'm glad you tagged me anyway; very interesting work going on here! :-)

**Comment by lirantal** [comment]
@david-a-wheeler last 2 commits address your feedback about the text of the lab.

**Comment by lirantal** [comment]
Alright, updated and rebased with sign-off now too 👌🏽 

Some screenshots showing hints and success
image

image

image

**Comment by lirantal** [comment]
@david-a-wheeler just a friendly nudge 🤗

**Comment by david-a-wheeler** [comment]
Thank you SO MUCH for persevering on this.

I think it'd be helpful to have more hints, and to make a little more
room for people to fix the response. But I think it'd be much easier to
merge this as it is, and then refine it further.

So I'll merge it, and then create a separate PR for proposed
improvements (which I hope you'll comment on!).

WONDERFUL! THANK YOU!

**Comment by david-a-wheeler** [comment]
Thank you! There's no *crisis* in having multiple labs for a topic, *especially* for an important one.

However, I urge you to look over our list here: <https://best.openssf.org/labs/> and find an important section where we have no lab at all. Those are the greatest needs. Thanks!

**Comment by lirantal** [comment]
> I think it'd be helpful to have more hints,

Happy to work on adding more. I focused first on getting it in with the most obvious first.

> find an important section where we have no lab at all. Those are the greatest needs. 

Definitely going to look more there and see what's a fun one to work on :-)
Thanks for merging and appreciate the follow-up PR. I'll meet you there for comments!

**Pull request merged**
