### PR TITLE
Propose tweaks to the introduction of the options guidance

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@thomasnyman @ran-dall - comments?

**Comment by david-a-wheeler** [comment]
Note: Markdown errors will continue until we fix the document. @ran-dall is working on that.

Since this document has a lot about applying lint-like tools, we probably ought to pass one too :=).

**Review by ran-dall — APPROVED** [review]
LGTM

**Comment by ran-dall** [comment]
@david-a-wheeler Shall I do the lint pass after you merge this?

**Review by gkunz — APPROVED** [review]

**Review by thomasnyman — APPROVED** [review]

**Pull request merged**
