### PR TITLE
Add threat model, goals, objectives

### PR DESCRIPTION
**Pull request by david-a-wheeler**
These are hinted at, but they should be clearly stated. This will make it much easier to justify the options below (including future options).

### CODE REVIEW

**Comment by thomasnyman** [comment]
I think this should be introduced together with changes that address #283. I would also expect mitigating memory-safety issues to be mentioned in the threat model. I would argue that is a more obvious use of the guide, but I don't have any objections for addressing underhanded code too in the threat model.

**Comment by david-a-wheeler** [comment]
**[thomasnyman](https://github.com/thomasnyman)**:

> I think this should be introduced together with changes that address https://github.com/ossf/wg-best-practices-os-developers/issues/283.

With respect, I think this needs to be added *first*. First, we need to make sure people understand the goals - otherwise it's not obvious *why* changes support the goals.

> I would also expect mitigating memory-safety issues to be mentioned in the threat model. I would argue that is a more obvious use of the guide, but I don't have any objections for addressing underhanded code too in the threat model.

That's a good idea. I think I can add a sentence at the end of a paragraph to make that clear *without* adding a lot of text.

**Comment by david-a-wheeler** [comment]
[thomasnyman](https://github.com/thomasnyman) - I've added a sentence to expressly note the importance of memory safety. I made a few minor tweaks in this section since I was there anyway.

**Comment by david-a-wheeler** [comment]
Note: I view this PR as a blocker for https://github.com/ossf/wg-best-practices-os-developers/issues/283 . Until we agree on the threat model we're supporting, it's hard to determine whether or not some specific flags are relevant.

**Comment by thomasnyman** [comment]
Turned inline links into references in footnotes to be consistent with the established style.

**Comment by thomasnyman** [comment]
Fixed broken link to Wikipedia article introduced in 6dff9b8abe1132648203a92170bb259fb884c2f9

**Review by thomasnyman — APPROVED** [review]

**Pull request merged**
