### PR TITLE
Update compiler guide contributors

### PR DESCRIPTION
**Pull request by thomasnyman**
Added recent contributors from GitHub and the C/C++ Compiler BP Calls. 

It's entirely possible I've missed someone, so please add to this PR if you realize someone is missing.

As with #185 I will reach out to these individuals to confirm they consent to be named in the guide before merging.

### CODE REVIEW

**Comment by thomasnyman** [comment]
So far, David Edelsohn has communicated their approval via e-mail.

**Comment by wphuhn-intel** [comment]
LGTM

**Comment by david-a-wheeler** [comment]
LGTM. Can we please merge this today? When people look at it tomorrow, I want to ensure that contributors who want credit get that credit.

**Comment by david-a-wheeler** [comment]
I see a bunch of "LGTM" and no objections.

I'm going to boldly merge this so these changes are *included*. We can always add more names with another PR, but I don't think we should wait.

**Pull request merged**
